version: '3.7'

services:
    nginx:
        build: ./nginx
        volumes:
          - static_volume:/home/app/web/static
          - ../certs:/etc/nginx/certs
        ports:
          - 80:80
          - 433:433
        depends_on:
          - web
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn Project_Capitalizer.wsgi:application --bind 0.0.0.0:8000
        volumes:
          - static_volume:/home/app/web/static
        expose:
          - 8000
        env_file:
          - ./.env.prod
        depends_on:
          - db
    db:
        image: postgres:12.0-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file:
          - ./.env.prod.db

volumes:
    postgres_data:
    static_volume:
