# Generated by Django 2.2.13 on 2020-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('interests', models.CharField(choices=[('int1', 'int1'), ('int2', 'int2'), ('int3', 'int3')], max_length=100)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
