# Generated by Django 2.2.13 on 2020-06-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('int1', 'int1'), ('int2', 'int2'), ('int3', 'int3')], max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['email'], 'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='interests',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='interests',
            field=models.ManyToManyField(related_name='userinfo', to='api.Interests'),
        ),
    ]
