# Generated by Django 2.2.13 on 2020-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200603_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['interest'],
            },
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.ManyToManyField(to='api.Interest'),
        ),
    ]
