# Generated by Django 2.2.13 on 2020-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200604_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.CharField(choices=[('int1', 'int1'), ('int2', 'int2'), ('int3', 'int3')], max_length=100),
        ),
    ]
